"""Black-box proof of Cargo-aware parity executable selection (§AR-009-surfaces.5.1)."""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import tempfile
import textwrap
import unittest
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[2]
PARITY_SCRIPT = REPOSITORY / "scripts" / "check_parity.py"
SCRATCH = Path.home() / "ag" / "tmp"

PARITY_SOURCE = """\
pub struct Ability {
    pub what: &'static str,
    pub keys: &'static [&'static str],
    pub command: &'static str,
}

pub const ABILITIES: &[Ability] = &[
    Ability {
        what: "read status",
        keys: &["x"],
        command: "status",
    },
];

pub const PRESENTATION: &[(&str, &str)] = &[
];
"""

CARGO_TOML = """\
[package]
name = "ephor"
version = "0.0.0"
edition = "2021"
"""

CARGO_LOCK = """\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "ephor"
version = "0.0.0"
"""

RUST_MAIN = r"""use std::fs::OpenOptions;
use std::io::Write;

fn main() {
    if let Ok(path) = std::env::var("PARITY_INVOCATION_LOG") {
        let mut log = OpenOptions::new().create(true).append(true).open(path).unwrap();
        writeln!(log, "{}", std::env::args().skip(1).collect::<Vec<_>>().join(" ")).unwrap();
    }
    println!("Usage: ephor status [OPTIONS]");
    println!("Options:\n      --json");
}
"""


class CheckParityCargoTargetTests(unittest.TestCase):
    def setUp(self) -> None:
        SCRATCH.mkdir(parents=True, exist_ok=True)
        self.temporary = tempfile.TemporaryDirectory(
            prefix="ephor-check-parity-", dir=SCRATCH
        )
        self.root = Path(self.temporary.name) / "fixture"
        (self.root / "scripts").mkdir(parents=True)
        (self.root / "src" / "api").mkdir(parents=True)
        (self.root / "src" / "feed" / "tui").mkdir(parents=True)
        shutil.copy2(PARITY_SCRIPT, self.root / "scripts" / "check_parity.py")
        (self.root / "src" / "api" / "parity.rs").write_text(
            PARITY_SOURCE, encoding="utf-8"
        )
        (self.root / "Cargo.toml").write_text(CARGO_TOML, encoding="utf-8")
        (self.root / "Cargo.lock").write_text(CARGO_LOCK, encoding="utf-8")
        (self.root / "src" / "main.rs").write_text(RUST_MAIN, encoding="utf-8")
        self.cargo_home = Path(self.temporary.name) / "cargo-home"
        self.cargo_home.mkdir()
        self.environment = os.environ.copy()
        self.environment["CARGO_HOME"] = str(self.cargo_home)
        self.environment.pop("CARGO_TARGET_DIR", None)
        self.environment.pop("CARGO_BUILD_TARGET_DIR", None)

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def run_parity(self, **environment: str) -> subprocess.CompletedProcess[str]:
        merged = self.environment | environment
        return subprocess.run(
            ["python3", "scripts/check_parity.py"],
            cwd=self.root,
            env=merged,
            capture_output=True,
            text=True,
            timeout=120,
        )

    def write_executable(
        self, path: Path, marker: Path, *, help_exit: int = 0
    ) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            textwrap.dedent(
                f"""\
                #!/bin/sh
                printf '%s\\n' "$*" >> {str(marker)!r}
                printf '%s\\n' 'Usage: ephor status [OPTIONS]' 'Options:' '      --json'
                if [ {help_exit} -ne 0 ]; then
                    printf '%s\\n' 'help exploded' >&2
                    exit {help_exit}
                fi
                """
            ),
            encoding="utf-8",
        )
        path.chmod(path.stat().st_mode | stat.S_IXUSR)

    def write_fake_cargo(
        self,
        target: Path,
        *,
        metadata_exit: int = 0,
        build_exit: int = 0,
    ) -> Path:
        fake_bin = Path(self.temporary.name) / "fake-bin"
        fake_bin.mkdir(exist_ok=True)
        cargo = fake_bin / "cargo"
        cargo.write_text(
            textwrap.dedent(
                f"""\
                #!/bin/sh
                if [ "$1" = metadata ]; then
                    if [ {metadata_exit} -ne 0 ]; then
                        printf '%s\\n' 'metadata exploded' >&2
                        exit {metadata_exit}
                    fi
                    printf '%s\\n' '{{"target_directory": "{target}"}}'
                    exit 0
                fi
                if [ "$1" = build ]; then
                    if [ {build_exit} -ne 0 ]; then
                        printf '%s\\n' 'build exploded' >&2
                        exit {build_exit}
                    fi
                    exit 0
                fi
                printf '%s\\n' "unexpected cargo command: $*" >&2
                exit 97
                """
            ),
            encoding="utf-8",
        )
        cargo.chmod(cargo.stat().st_mode | stat.S_IXUSR)
        return fake_bin

    def assert_operational_failure(
        self,
        result: subprocess.CompletedProcess[str],
        action: str,
        target: Path | None = None,
    ) -> str:
        self.assertEqual(result.returncode, 2, result.stdout + result.stderr)
        self.assertEqual(result.stdout, "")
        self.assertIn(f"parity: cannot {action} ephor", result.stderr)
        self.assertNotIn("Traceback", result.stderr)
        self.assertNotIn("FileNotFoundError", result.stderr)
        if target is not None:
            debug = target / "debug" / "ephor"
            release = target / "release" / "ephor"
            self.assertIn(str(debug), result.stderr)
            self.assertIn(str(release), result.stderr)
            self.assertIn(
                f"CARGO_TARGET_DIR={target} cargo build --locked", result.stderr
            )
            self.assertIn(str(self.root), result.stderr)
        return result.stderr

    def test_configured_external_target_is_authoritative_over_checkout_target(self) -> None:
        external = Path(self.temporary.name) / "external-target"
        external_log = Path(self.temporary.name) / "external.log"
        local_log = Path(self.temporary.name) / "local.log"
        self.write_executable(external / "debug" / "ephor", external_log)
        self.write_executable(self.root / "target" / "debug" / "ephor", local_log)

        result = self.run_parity(CARGO_TARGET_DIR=str(external))

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(external_log.exists(), "configured external binary was not launched")
        self.assertEqual(external_log.read_text(encoding="utf-8"), "status --help\n")
        self.assertFalse(local_log.exists())

    def test_relative_cargo_target_dir_is_based_at_repository_root(self) -> None:
        selected = self.root / "relative-target"
        selected_log = Path(self.temporary.name) / "relative.log"
        local_log = Path(self.temporary.name) / "local.log"
        self.write_executable(selected / "debug" / "ephor", selected_log)
        self.write_executable(self.root / "target" / "debug" / "ephor", local_log)

        result = self.run_parity(CARGO_TARGET_DIR="relative-target")

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(selected_log.exists(), "relative target binary was not launched")
        self.assertEqual(selected_log.read_text(encoding="utf-8"), "status --help\n")
        self.assertFalse(local_log.exists())

    def test_relative_cargo_configuration_is_based_at_dot_cargo_parent(self) -> None:
        configured = self.root / "configured-target"
        configured_log = Path(self.temporary.name) / "configured.log"
        local_log = Path(self.temporary.name) / "local.log"
        (self.root / ".cargo").mkdir()
        (self.root / ".cargo" / "config.toml").write_text(
            '[build]\ntarget-dir = "configured-target"\n', encoding="utf-8"
        )
        self.write_executable(configured / "debug" / "ephor", configured_log)
        self.write_executable(self.root / "target" / "debug" / "ephor", local_log)

        result = self.run_parity()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(configured_log.exists(), "Cargo-configured binary was not launched")
        self.assertEqual(configured_log.read_text(encoding="utf-8"), "status --help\n")
        self.assertFalse(local_log.exists())

    def test_environment_target_overrides_cargo_configuration(self) -> None:
        configured = self.root / "configured-target"
        environment_target = Path(self.temporary.name) / "environment-target"
        configured_log = Path(self.temporary.name) / "configured.log"
        environment_log = Path(self.temporary.name) / "environment.log"
        local_log = Path(self.temporary.name) / "local.log"
        (self.root / ".cargo").mkdir()
        (self.root / ".cargo" / "config.toml").write_text(
            '[build]\ntarget-dir = "configured-target"\n', encoding="utf-8"
        )
        self.write_executable(configured / "debug" / "ephor", configured_log)
        self.write_executable(
            environment_target / "debug" / "ephor", environment_log
        )
        self.write_executable(self.root / "target" / "debug" / "ephor", local_log)

        result = self.run_parity(CARGO_TARGET_DIR=str(environment_target))

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue(environment_log.exists(), "environment target binary was not launched")
        self.assertEqual(environment_log.read_text(encoding="utf-8"), "status --help\n")
        self.assertFalse(configured_log.exists())
        self.assertFalse(local_log.exists())

    def test_unconfigured_debug_precedes_release(self) -> None:
        debug_log = Path(self.temporary.name) / "debug.log"
        release_log = Path(self.temporary.name) / "release.log"
        self.write_executable(self.root / "target" / "debug" / "ephor", debug_log)
        self.write_executable(self.root / "target" / "release" / "ephor", release_log)

        result = self.run_parity()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(debug_log.read_text(encoding="utf-8"), "status --help\n")
        self.assertFalse(release_log.exists())

    def test_unconfigured_release_is_used_when_debug_is_absent(self) -> None:
        release_log = Path(self.temporary.name) / "release.log"
        self.write_executable(self.root / "target" / "release" / "ephor", release_log)

        result = self.run_parity()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertEqual(release_log.read_text(encoding="utf-8"), "status --help\n")

    def test_standalone_check_builds_debug_binary_in_resolved_target(self) -> None:
        target = Path(self.temporary.name) / "standalone-target"
        invocation_log = Path(self.temporary.name) / "built.log"

        result = self.run_parity(
            CARGO_TARGET_DIR=str(target),
            PARITY_INVOCATION_LOG=str(invocation_log),
        )

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertTrue((target / "debug" / "ephor").is_file())
        self.assertEqual(invocation_log.read_text(encoding="utf-8"), "status --help\n")

    def test_metadata_failure_is_actionable_exit_two(self) -> None:
        target = Path(self.temporary.name) / "unresolved-target"
        local_log = Path(self.temporary.name) / "local.log"
        fake_bin = self.write_fake_cargo(target, metadata_exit=19)
        self.write_executable(self.root / "target" / "debug" / "ephor", local_log)

        result = self.run_parity(PATH=f"{fake_bin}:{self.environment['PATH']}")

        diagnostic = self.assert_operational_failure(result, "resolve")
        self.assertIn("metadata exploded", diagnostic)
        self.assertIn(
            "cargo metadata --no-deps --format-version 1 --locked", diagnostic
        )
        self.assertFalse(local_log.exists())

    def test_build_failure_is_actionable_exit_two(self) -> None:
        target = Path(self.temporary.name) / "failed-build-target"
        fake_bin = self.write_fake_cargo(target, build_exit=23)

        result = self.run_parity(PATH=f"{fake_bin}:{self.environment['PATH']}")

        diagnostic = self.assert_operational_failure(result, "build", target)
        self.assertIn("build exploded", diagnostic)

    def test_successful_build_without_ephor_is_actionable_exit_two(self) -> None:
        target = Path(self.temporary.name) / "empty-build-target"
        fake_bin = self.write_fake_cargo(target)

        result = self.run_parity(PATH=f"{fake_bin}:{self.environment['PATH']}")

        diagnostic = self.assert_operational_failure(result, "build", target)
        self.assertIn("did not produce", diagnostic)

    def test_unlaunchable_executable_is_actionable_exit_two(self) -> None:
        target = self.root / "target"
        selected = target / "debug" / "ephor"
        selected.parent.mkdir(parents=True)
        selected.write_text("not executable\n", encoding="utf-8")

        result = self.run_parity()

        diagnostic = self.assert_operational_failure(result, "launch", target)
        self.assertIn(str(selected), diagnostic)
        self.assertIn("Permission denied", diagnostic)

    def test_nonzero_help_remains_a_parity_finding(self) -> None:
        marker = Path(self.temporary.name) / "failed-help.log"
        self.write_executable(
            self.root / "target" / "debug" / "ephor", marker, help_exit=9
        )

        result = self.run_parity()

        self.assertEqual(result.returncode, 1, result.stdout + result.stderr)
        self.assertIn("Abilities whose command has no machine form", result.stderr)
        self.assertIn("help exploded", result.stderr)
        self.assertNotIn("parity: cannot", result.stderr)
        self.assertNotIn("Traceback", result.stderr)

    def test_success_remains_exit_zero(self) -> None:
        marker = Path(self.temporary.name) / "success.log"
        self.write_executable(self.root / "target" / "debug" / "ephor", marker)

        result = self.run_parity()

        self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
        self.assertIn("every command has --json", result.stdout)
        self.assertEqual(result.stderr, "")


if __name__ == "__main__":
    unittest.main()
